export const majorScales = {
  A1: {
    scaleTones: [
      { tone: "A", degree: 0 },
      { tone: "A#", degree: 1 },
      { tone: "B", degree: 2 },
      { tone: "C", degree: 3 },
      { tone: "C#", degree: 4 },
      { tone: "D", degree: 5 },
      { tone: "D#", degree: 6 },
      { tone: "E", degree: 7 },
      { tone: "F", degree: 8 },
      { tone: "F#", degree: 9 },
      { tone: "G", degree: 10 },
      { tone: "G#", degree: 11 },
    ],
    lowestToneFreq: 55,
    highestToneFreq: 103.83,
    octaveToneFreq: 110,
  },
  C2: {
    scaleTones: [
      { tone: "C", degree: 0, frequency: 65.41 },
      { tone: "C#", degree: 1, frequency: 69.30 },
      { tone: "D", degree: 2, frequency: 73.42 },
      { tone: "D#", degree: 3, frequency: 77.78 },
      { tone: "E", degree: 4, frequency: 82.41 },
      { tone: "F", degree: 5, frequency: 87.31 },
      { tone: "F#", degree: 6, frequency: 92.50 },
      { tone: "G", degree: 7, frequency: 98.00 },
      { tone: "G#", degree: 8, frequency: 103.83 },
      { tone: "A", degree: 9, frequency: 110.00 },
      { tone: "A#", degree: 10, frequency: 116.54 },
      { tone: "B", degree: 11, frequency: 123.47 },
    ],
    lowestToneFreq: 65.41,
    highestToneFreq: 123.47,
    octaveToneFreq: 130.81,
  },
  Chromatic: {
    scaleTones: [
      { tone: "C", degree: 0 },
      { tone: "C#", degree: 1 },
      { tone: "D", degree: 2 },
      { tone: "D#", degree: 3 },
      { tone: "E", degree: 4 },
      { tone: "F", degree: 5 },
      { tone: "F#", degree: 6 },
      { tone: "G", degree: 7 },
      { tone: "G#", degree: 8 },
      { tone: "A", degree: 9 },
      { tone: "A#", degree: 10 },
      { tone: "B", degree: 11 },
    ],
    lowestToneFreq: 261.63,
    highestToneFreq: 493.88,
    octaveToneFreq: 523.25,
  },
};
