export const majorScales = {
  A1: {
    scaleTones: [
      { tone: "A", degree: 0 },
      { tone: "A#", degree: 1 },
      { tone: "B", degree: 2 },
      { tone: "C", degree: 3 },
      { tone: "C#", degree: 4 },
      { tone: "D", degree: 5 },
      { tone: "D#", degree: 6 },
      { tone: "E", degree: 7 },
      { tone: "F", degree: 8 },
      { tone: "F#", degree: 9 },
      { tone: "G", degree: 10 },
      { tone: "G#", degree: 11 },
    ],
    lowestToneFreq: 55,
    highestToneFreq: 103.83,
    octaveToneFreq: 110,
  },
  E2: {
    scaleTones: ["E", "F#", "G#", "A", "B", "C#", "D#"],
    lowestToneFreq: 82.41,
    highestToneFreq: 155.56,
    octaveToneFreq: 164.81,
  },
  "F#2": {
    scaleTones: ["F#", "G#", "A#", "B", "C#", "D#", "E#"],
    lowestToneFreq: 92.5,
    highestToneFreq: 174.61,
    octaveToneFreq: 184.99,
  },
  Bb3: {
    scaleTones: ["Bb", "C", "D", "Eb", "F", "G", "A"],
    lowestToneFreq: 233.08,
    highestToneFreq: 440,
    octaveToneFreq: 466.16,
  },
  C4: {
    scaleTones: ["C", "D", "E", "F", "G", "A", "B"],
    lowestToneFreq: 261.63,
    highestToneFreq: 493.88,
    octaveToneFreq: 523.25,
  },
  Chromatic: {
    scaleTones: [
      { tone: "C", degree: 0 },
      { tone: "C#", degree: 1 },
      { tone: "D", degree: 2 },
      { tone: "D#", degree: 3 },
      { tone: "E", degree: 4 },
      { tone: "F", degree: 5 },
      { tone: "F#", degree: 6 },
      { tone: "G", degree: 7 },
      { tone: "G#", degree: 8 },
      { tone: "A", degree: 9 },
      { tone: "A#", degree: 10 },
      { tone: "B", degree: 11 },
    ],
    lowestToneFreq: 261.63,
    highestToneFreq: 493.88,
    octaveToneFreq: 523.25,
  },
};
